name: push-pipeline
on:
  push:
    branches:
      - gh-update
      - ^v[0-9]*.[0-9]*.x$
    tags:
      - "*"
defaults:
  run:
    working-directory: chaoscenter
    shell: bash

jobs:
  get-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: |
          img_tag=""
          array=(`echo ${GITHUB_REF} | sed 's/\//\n/g'`)
          if [ ${array[1]} == "tags" ]
          then
              echo "tag build"
              img_tag=${GITHUB_REF#refs/*/}
          else
              echo "non tag build"
              img_tag="ci"
          fi
          # This is a condition where image tag looks like "pull/<pullrequest-name>" during pull request build
          NEW_IMG_TAG=`echo $img_tag | sed "s/\//-/g"`
          echo $NEW_IMG_TAG
          echo export IMG_TAG=$NEW_IMG_TAG >> env-vars
          echo export GRAPHQL_SERVER_IMAGE="litmusportal-server" >> env-vars
          echo export AUTHENTICATION_SERVER_IMAGE="litmusportal-auth-server" >> env-vars
          echo export FRONTEND_IMAGE="litmusportal-frontend" >> env-vars
          echo export SUBSCRIBER_IMAGE="litmusportal-subscriber" >> env-vars
          echo export EVENT_TRACKER="litmusportal-event-tracker" >> env-vars
          echo export UPGRADE_AGENT_CP="upgrade-agent-cp" >> env-vars
          echo export DEX_SERVER="litmusportal-dex-server" >> env-vars

      - name: Uploading envs
        uses: actions/upload-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal/env-vars

  docker-build-and-push-graphql-server:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push graphql server docker image
        env:
          IMAGE_NAME: ${GRAPHQL_SERVER_IMAGE}
          IMG_TAG: ${IMG_TAG}
          PLATFORMS: ${{ secrets.PLATFORMS }}
          REPONAME: ${{ secrets.REPONAME }}
          DIRECTORY: "graphql/server"
        run: |
          source env-vars
          make push-portal-component
          

  docker-build-and-push-authentication-server:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push auth server docker image
        env:
          IMAGE_NAME: ${AUTHENTICATION_SERVER_IMAGE}
          IMG_TAG: ${IMG_TAG}
          PLATFORMS: ${{ secrets.PLATFORMS }}
          REPONAME: ${{ secrets.REPONAME }}
          DIRECTORY: "authentication"
        run: |
          source env-vars
          make push-portal-component
          

  docker-build-and-push-subscriber:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push subscriber docker image
        env:
          IMAGE_NAME: ${SUBSCRIBER_IMAGE}
          IMG_TAG: ${IMG_TAG}
          PLATFORMS: ${{ secrets.PLATFORMS }}
          REPONAME: ${{ secrets.REPONAME }}
          DIRECTORY: "subscriber"
        run: |
          source env-vars
          make push-portal-component

